language: node_js
jobs:
  include:
    - stage: deploy to amazon
      script: skip
      deploy:
        provider: s3
        access_key_id: $AWS_KEY_ID
        secret_access_key: $AWS_SECRET_KEY
        bucket: "rotlis-test1"
